server:
  port: 9090

spring:
  datasource:
    url: jdbc:oracle:thin:@172.17.11.24:1521:DS6CM
    username: rak
    password: rak
    driver-class-name: oracle.jdbc.OracleDriver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: null

jwt:
  secret: MySuperSecretKeyForJWTTokenGeneration2024MustBe256BitsLong
  expiry-seconds: 1800
  remember-me-expiry-seconds: 86400

wechat:
  app-id: wx6916aae979a43d9e
  app-secret: 2c739e9d107fb0fc5d1cfc25dd9857f8
  callback-url: http://localhost:9090/api/v1/auth/wechat/callback
